### ISSUE TITLE
tomcat:latest does not work with current Spring Boot

### ISSUE THREAD

**Issue by ErasedRhythm** [iamvickyav/SpringBoot-Docker-Tomcat#1]
Hi! First of all, thanks for the repository. I had many struggles to get a war that is working on a Tomcat server.

Here to the problem that I have never stumbled upon an answer anywhere:

`tomcat:latest` downloads the latest version which is Tomcat 10 is _not supported_ by Spring Boot currently and will only [get support for it in Q4 2022](https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6) together with the requirement to use Java 17. 

Therefore you need to downgrade to a Tomcat 9 version or whichever is supported by your Spring Boot version. You can find the supported version in the dependency tree or if you inspect the parent of your pom.xml.

I hope at least someone will save themself a lot of time.

**Comment by iamvickyav** [comment]
Hi @ErasedRhythm , Thanks for bringing this up. Will fix this ...

**Comment by iamvickyav** [comment]
Fixed the issue. Thanks again @ErasedRhythm
